name: Docs
on:
    push:
        branches:
            - master

jobs:
    docs:
        name: Docs
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 5.0.x
            - run: choco install docfx -y

            - run: docfx docs/docfx.json

            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: _docs
