name: Tests
on: [push, pull_request]

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 5.0.x

            - run: dotnet test
              working-directory: AtlasRhythm.Cryptography.Tests
